parameters:
#    bkfk_landing.example.class: Bkfk\LandingBundle\Example

services:
#    bkfk_landing.example:
#        class: %bkfk_landing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
