bkfk_user:
    resource: "@BkfkUserBundle/Controller/"
    type:     annotation
    prefix:   /

bkfk_store:
    resource: "@BkfkStoreBundle/Resources/config/routing.yml"
    prefix:   /store

bkfk_landing:
    resource: "@BkfkLandingBundle/Resources/config/routing.yml"
    prefix:   /

