<?php
/**
 * Created by JetBrains PhpStorm.
 * User: poldotz
 * Date: 01/04/13
 * Time: 7.13
 * To change this template use File | Settings | File Templates.
 */

namespace Bkfk\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
}
